# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

# This example demonstrates how to create an Amazon Managed Service for Prometheus (AMP) Scraper
# that collects metrics from an Amazon EKS cluster.
#
# Prerequisites:
# - An existing EKS cluster
# - VPC subnets where the scraper will run
# - Security groups for the scraper
# - An IAM role with appropriate permissions

apiVersion: amp.aws.upbound.io/v1beta1
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: amp/v1beta1/scraper
    crossplane.io/external-name: ws-5db06661-42b2-4ecc-a0e9-a0e3065081e6
  labels:
    testing.upbound.io/example-name: amp-provider-test-workspace
  name: amp-provider-test-workspace
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: eks-containersmanagement-161436383136-aws-provider
---
apiVersion: amp.aws.upbound.io/v1beta1
kind: Scraper
metadata:
  annotations:
    meta.upbound.io/example-id: amp/v1beta1/scraper
    crossplane.io/external-name: s-b6fc218d-daee-4745-b5ef-adaab2779379
  labels:
    testing.upbound.io/example-name: amp-provider-test-scraper
  name: amp-provider-test-scraper
spec:
  forProvider:
    region: us-east-1
    destination:
    - amp:
      - workspaceArnRef:
          name: amp-provider-test-workspace
    source:
    - eks:
      - clusterArn: arn:aws:eks:us-east-1:161436383136:cluster/eks-containersmanagement
        subnetIds:
        - subnet-078e3d9b9f4b48e20
        - subnet-020bce96a3715a57c
        - subnet-0a52fa0b5cecd9676
        - subnet-07e14b8bc77876364
        - subnet-03ec8e7a7aadabe2b
        securityGroupIds:
        - sg-0eed3a517fc35c007
        - sg-036c56490d8432a97
    scrapeConfiguration: |
      global:
        scrape_interval: 30s
      scrape_configs:
        # Scrape pod metrics
        - job_name: pod_exporter
          kubernetes_sd_configs:
            - role: pod
        # Scrape container metrics via cAdvisor
        - job_name: cadvisor
          scheme: https
          authorization:
            credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - replacement: kubernetes.default.svc:443
              target_label: __address__
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        # Scrape Kubernetes API server metrics
        - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          job_name: kubernetes-apiservers
          kubernetes_sd_configs:
          - role: endpoints
          relabel_configs:
          - action: keep
            regex: default;kubernetes;https
            source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_service_name
            - __meta_kubernetes_endpoint_port_name
          scheme: https
        # Scrape kube-proxy metrics
        - job_name: kube-proxy
          honor_labels: true
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - action: keep
            source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_name
            separator: '/'
            regex: 'kube-system/kube-proxy.+'
          - source_labels:
            - __address__
            action: replace
            target_label: __address__
            regex: (.+?)(\\:\\d+)?
            replacement: $1:10249
  providerConfigRef:
    name: eks-containersmanagement-161436383136-aws-provider